### ISSUE TITLE
iOS 16 beta 6 developer disk image 

### ISSUE THREAD

**Issue by Dantee296** [justanobody2107/AppleDeveloperDiskImages#1]
hey , do we have it available ?
the currently uploaded image not mounting on beta 6

**Comment by singlekeycap** [comment]
I'm updating Xcode now, give me an hour or two and the new image should be up.

**Comment by singlekeycap** [comment]
The new image is up, if it still doesn't work wait till the new Xcode beta comes out and the updated one will be uploaded within the week.

**Comment by Dantee296** [comment]
JFYI , it didnt work on beta6

**Comment by singlekeycap** [comment]
I will test it on a friend's device and get back to you then. It'll take me a couple of days though, as I am busy tomorrow and the day after.

**Comment by singlekeycap** [comment]
Alright, I had a friend test on his device on iOS 16b6, and it worked. Could you tell me the steps you took to install this image?

**Comment by Dantee296** [comment]
that's strange , i'm using ideviceimage mounter to mount on iPhoneSe 2nd gen iOS b6

**Comment by Dantee296** [comment]
```
./ideviceimagemounter /Users/test/Downloads/DeveloperDiskImage.dmg 
/Users/test/Downloads/DeveloperDiskImage.dmg.signature

Uploading /Users/test/Downloads/DeveloperDiskImage.dmg
done.
Mounting...
Error: ImageMountFailed
```

**Comment by singlekeycap** [comment]
Hmm, I'm not too sure what's wrong here. I would make sure the device is properly paired and trusted, and then try getting into the directory the files are and going just by their name. Also, are you on the latest version of libimobiledevice?

**Comment by Dantee296** [comment]
can u please provide the latest files here again for iOS16b6

**Comment by singlekeycap** [comment]
The files are linked [here](https://github.com/justanobody2107/AppleDeveloperDiskImages/releases/tag/iOS16), unfortunately I am on mobile and have no idea how to attach them. I am certain this is the latest image from Xcode 14b5

**Comment by Dantee296** [comment]
found issue , developer mode needed to be enabled

**Comment by singlekeycap** [comment]
Glad to hear you were able to sort it out, I will add that as a precaution to the installation steps. Have fun with the dev stuff!
